//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hnliving.web.ServiceReferenceJava {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.ss.org/", ConfigurationName="ServiceReferenceJava.WebServiceImpl")]
    public interface WebServiceImpl {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ss.org/WebServiceImpl/saveRequest", ReplyAction="http://ws.ss.org/WebServiceImpl/saveResponse")]
        hnliving.web.ServiceReferenceJava.saveResponse save(hnliving.web.ServiceReferenceJava.saveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ss.org/WebServiceImpl/saveRequest", ReplyAction="http://ws.ss.org/WebServiceImpl/saveResponse")]
        System.Threading.Tasks.Task<hnliving.web.ServiceReferenceJava.saveResponse> saveAsync(hnliving.web.ServiceReferenceJava.saveRequest request);
        
        // CODEGEN: 命名空间  的元素名称 return 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ss.org/WebServiceImpl/sayHelloRequest", ReplyAction="http://ws.ss.org/WebServiceImpl/sayHelloResponse")]
        hnliving.web.ServiceReferenceJava.sayHelloResponse sayHello(hnliving.web.ServiceReferenceJava.sayHelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.ss.org/WebServiceImpl/sayHelloRequest", ReplyAction="http://ws.ss.org/WebServiceImpl/sayHelloResponse")]
        System.Threading.Tasks.Task<hnliving.web.ServiceReferenceJava.sayHelloResponse> sayHelloAsync(hnliving.web.ServiceReferenceJava.sayHelloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="save", Namespace="http://ws.ss.org/", Order=0)]
        public hnliving.web.ServiceReferenceJava.saveRequestBody Body;
        
        public saveRequest() {
        }
        
        public saveRequest(hnliving.web.ServiceReferenceJava.saveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public saveRequestBody() {
        }
        
        public saveRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveResponse", Namespace="http://ws.ss.org/", Order=0)]
        public hnliving.web.ServiceReferenceJava.saveResponseBody Body;
        
        public saveResponse() {
        }
        
        public saveResponse(hnliving.web.ServiceReferenceJava.saveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public saveResponseBody() {
        }
        
        public saveResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sayHelloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sayHello", Namespace="http://ws.ss.org/", Order=0)]
        public hnliving.web.ServiceReferenceJava.sayHelloRequestBody Body;
        
        public sayHelloRequest() {
        }
        
        public sayHelloRequest(hnliving.web.ServiceReferenceJava.sayHelloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sayHelloRequestBody {
        
        public sayHelloRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sayHelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sayHelloResponse", Namespace="http://ws.ss.org/", Order=0)]
        public hnliving.web.ServiceReferenceJava.sayHelloResponseBody Body;
        
        public sayHelloResponse() {
        }
        
        public sayHelloResponse(hnliving.web.ServiceReferenceJava.sayHelloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sayHelloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public sayHelloResponseBody() {
        }
        
        public sayHelloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceImplChannel : hnliving.web.ServiceReferenceJava.WebServiceImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceImplClient : System.ServiceModel.ClientBase<hnliving.web.ServiceReferenceJava.WebServiceImpl>, hnliving.web.ServiceReferenceJava.WebServiceImpl {
        
        public WebServiceImplClient() {
        }
        
        public WebServiceImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hnliving.web.ServiceReferenceJava.saveResponse hnliving.web.ServiceReferenceJava.WebServiceImpl.save(hnliving.web.ServiceReferenceJava.saveRequest request) {
            return base.Channel.save(request);
        }
        
        public string save(string arg0, string arg1) {
            hnliving.web.ServiceReferenceJava.saveRequest inValue = new hnliving.web.ServiceReferenceJava.saveRequest();
            inValue.Body = new hnliving.web.ServiceReferenceJava.saveRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            hnliving.web.ServiceReferenceJava.saveResponse retVal = ((hnliving.web.ServiceReferenceJava.WebServiceImpl)(this)).save(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hnliving.web.ServiceReferenceJava.saveResponse> hnliving.web.ServiceReferenceJava.WebServiceImpl.saveAsync(hnliving.web.ServiceReferenceJava.saveRequest request) {
            return base.Channel.saveAsync(request);
        }
        
        public System.Threading.Tasks.Task<hnliving.web.ServiceReferenceJava.saveResponse> saveAsync(string arg0, string arg1) {
            hnliving.web.ServiceReferenceJava.saveRequest inValue = new hnliving.web.ServiceReferenceJava.saveRequest();
            inValue.Body = new hnliving.web.ServiceReferenceJava.saveRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((hnliving.web.ServiceReferenceJava.WebServiceImpl)(this)).saveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        hnliving.web.ServiceReferenceJava.sayHelloResponse hnliving.web.ServiceReferenceJava.WebServiceImpl.sayHello(hnliving.web.ServiceReferenceJava.sayHelloRequest request) {
            return base.Channel.sayHello(request);
        }
        
        public string sayHello() {
            hnliving.web.ServiceReferenceJava.sayHelloRequest inValue = new hnliving.web.ServiceReferenceJava.sayHelloRequest();
            inValue.Body = new hnliving.web.ServiceReferenceJava.sayHelloRequestBody();
            hnliving.web.ServiceReferenceJava.sayHelloResponse retVal = ((hnliving.web.ServiceReferenceJava.WebServiceImpl)(this)).sayHello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<hnliving.web.ServiceReferenceJava.sayHelloResponse> hnliving.web.ServiceReferenceJava.WebServiceImpl.sayHelloAsync(hnliving.web.ServiceReferenceJava.sayHelloRequest request) {
            return base.Channel.sayHelloAsync(request);
        }
        
        public System.Threading.Tasks.Task<hnliving.web.ServiceReferenceJava.sayHelloResponse> sayHelloAsync() {
            hnliving.web.ServiceReferenceJava.sayHelloRequest inValue = new hnliving.web.ServiceReferenceJava.sayHelloRequest();
            inValue.Body = new hnliving.web.ServiceReferenceJava.sayHelloRequestBody();
            return ((hnliving.web.ServiceReferenceJava.WebServiceImpl)(this)).sayHelloAsync(inValue);
        }
    }
}
